#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

# External gate for https://github.com/jasl/vllm/issues/12.
# The harness does not vendor the W4A16 artifact or AIME runner. The caller
# supplies both while this profile fixes the reported vLLM serve shape.
ISSUE12_W4A16_MODEL="${ISSUE12_W4A16_MODEL:-}"
ISSUE12_AIME_RUNNER_COMMAND="${ISSUE12_AIME_RUNNER_COMMAND:-}"

if [[ -z "${ISSUE12_W4A16_MODEL}" ]]; then
  printf '%s\n' "ISSUE12_W4A16_MODEL must point to the W4A16 artifact" >&2
  exit 2
fi
if [[ -z "${ISSUE12_AIME_RUNNER_COMMAND}" ]]; then
  printf '%s\n' "ISSUE12_AIME_RUNNER_COMMAND must be set" >&2
  exit 2
fi

MODEL="${ISSUE12_W4A16_MODEL}"
ISSUE12_SERVED_MODEL_NAME="${ISSUE12_SERVED_MODEL_NAME:-DSV4-W4A16-FP8-MTP}"
B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-sm120_issue12_w4a16_marlin_aime_c4}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp1}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-external_command}"
RUN_EXTERNAL_COMMAND="${RUN_EXTERNAL_COMMAND:-1}"
EXTERNAL_COMMAND="${EXTERNAL_COMMAND:-${ISSUE12_AIME_RUNNER_COMMAND}}"
EXTERNAL_COMMAND_LABEL="${EXTERNAL_COMMAND_LABEL:-issue12_w4a16_marlin_aime_c4}"
EXTERNAL_COMMAND_TIMEOUT="${EXTERNAL_COMMAND_TIMEOUT:-14400}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-4}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-65536}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-disabled}"
B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}"
B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}"
SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}"
VLLM_TRITON_MLA_SPARSE="${VLLM_TRITON_MLA_SPARSE:-1}"
VLLM_TRITON_MLA_SPARSE_HEAD_BLOCK_SIZE="${VLLM_TRITON_MLA_SPARSE_HEAD_BLOCK_SIZE:-4}"
VLLM_USE_FLASHINFER_SAMPLER="${VLLM_USE_FLASHINFER_SAMPLER:-0}"
VLLM_ALLOW_LONG_MAX_MODEL_LEN="${VLLM_ALLOW_LONG_MAX_MODEL_LEN:-1}"

if [[ -z "${B200_EXTRA_SERVE_ARGS+x}" ]]; then
  B200_EXTRA_SERVE_ARGS="--served-model-name ${ISSUE12_SERVED_MODEL_NAME} --gpu-memory-utilization 0.92 --max-num-seqs 8 --max-num-batched-tokens 8192 --load-format safetensors --disable-custom-all-reduce --default-chat-template-kwargs '{\"thinking\": true}' --compilation-config '{\"cudagraph_mode\":\"FULL_AND_PIECEWISE\",\"custom_ops\":[\"all\"]}' --override-generation-config '{\"temperature\": 1.0, \"top_p\": 1.0}'"
fi

export ISSUE12_W4A16_MODEL ISSUE12_AIME_RUNNER_COMMAND
export ISSUE12_SERVED_MODEL_NAME MODEL B200_BASELINE_LABEL
export B200_BASELINE_VARIANTS B200_BASELINE_PHASES RUN_EXTERNAL_COMMAND
export EXTERNAL_COMMAND EXTERNAL_COMMAND_LABEL EXTERNAL_COMMAND_TIMEOUT
export B200_TENSOR_PARALLEL_SIZE SERVE_MAX_MODEL_LEN SERVE_PREFIX_CACHE_MODE
export B200_BLOCK_SIZE B200_KV_CACHE_DTYPE SERVE_USE_FP4_INDEXER_CACHE
export VLLM_TRITON_MLA_SPARSE VLLM_TRITON_MLA_SPARSE_HEAD_BLOCK_SIZE
export VLLM_USE_FLASHINFER_SAMPLER VLLM_ALLOW_LONG_MAX_MODEL_LEN
export B200_EXTRA_SERVE_ARGS

"${SCRIPT_DIR}/run_b200_baseline.sh"
