#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

# Reduced gate for a user-reported DP/EP long-context stability issue:
# DP=3 + EP, 256K max model length, prefix cache enabled, chunked prefill,
# MTP=2, FP8 KV, FULL_AND_PIECEWISE, and long-running traffic eventually hit:
# - RuntimeWarning / runtime JIT debt
# - Triton kernel JIT compilation during inference
# - TileLang begins to compile kernel `mhc_pre_big_fuse_with_norm_tilelang`
# - Triton Error [CUDA]: out of memory
# - Connection closed by peer after one worker crashes
# - Process ApiServer_* died with exit code None
#
# Defaults are intentionally reduced so the gate can run on smaller SM12x
# development hosts. To mirror the external shape on a matching host, override:
# B200_DATA_PARALLEL_SIZE=3 SERVE_MAX_MODEL_LEN=262144
# STREAMING_PRESSURE_LINE_COUNT=8000 STREAMING_PRESSURE_CONCURRENCY=8

shell_quote() {
  printf '%q' "$1"
}

SM12X_DP_EP_OOM_LABEL="${SM12X_DP_EP_OOM_LABEL:-user_report_4619507132_dp_ep_oom_reduced}"
SM12X_DP_EP_OOM_GPU_MEMORY_UTILIZATION="${SM12X_DP_EP_OOM_GPU_MEMORY_UTILIZATION:-0.95}"
SM12X_DP_EP_OOM_MAX_NUM_SEQS="${SM12X_DP_EP_OOM_MAX_NUM_SEQS:-16}"
SM12X_DP_EP_OOM_MAX_NUM_BATCHED_TOKENS="${SM12X_DP_EP_OOM_MAX_NUM_BATCHED_TOKENS:-8192}"

B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-${SM12X_DP_EP_OOM_LABEL}}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-prefix_cache_stress,streaming_pressure_soak}"
B200_DATA_PARALLEL_SIZE="${B200_DATA_PARALLEL_SIZE:-2}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-1}"
B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}"
B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-131072}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-enabled}"
SERVE_ENABLE_EXPERT_PARALLEL="${SERVE_ENABLE_EXPERT_PARALLEL:-1}"
SERVE_ENABLE_CHUNKED_PREFILL="${SERVE_ENABLE_CHUNKED_PREFILL:-1}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-sm12x_dp_ep_oom_reduced}"

RUN_PREFIX_CACHE_STRESS="${RUN_PREFIX_CACHE_STRESS:-1}"
PREFIX_CACHE_STRESS_CASE_NAME="${PREFIX_CACHE_STRESS_CASE_NAME:-dp_ep_oom_prefix_cache_stress}"
PREFIX_CACHE_STRESS_TRIALS="${PREFIX_CACHE_STRESS_TRIALS:-8}"
PREFIX_CACHE_STRESS_FILLER_WORDS="${PREFIX_CACHE_STRESS_FILLER_WORDS:-3200}"
PREFIX_CACHE_STRESS_TURNS="${PREFIX_CACHE_STRESS_TURNS:-6}"
PREFIX_CACHE_STRESS_MAX_TOKENS="${PREFIX_CACHE_STRESS_MAX_TOKENS:-256}"
PREFIX_CACHE_STRESS_TEMPERATURE="${PREFIX_CACHE_STRESS_TEMPERATURE:-1.0}"
PREFIX_CACHE_STRESS_TOP_P="${PREFIX_CACHE_STRESS_TOP_P:-1.0}"
PREFIX_CACHE_STRESS_TIMEOUT="${PREFIX_CACHE_STRESS_TIMEOUT:-900}"

RUN_STREAMING_PRESSURE_SOAK="${RUN_STREAMING_PRESSURE_SOAK:-1}"
STREAMING_PRESSURE_CASE_NAME="${STREAMING_PRESSURE_CASE_NAME:-dp_ep_oom_streaming_pressure_soak}"
STREAMING_PRESSURE_CONCURRENCY="${STREAMING_PRESSURE_CONCURRENCY:-4}"
STREAMING_PRESSURE_ROUND_COUNT="${STREAMING_PRESSURE_ROUND_COUNT:-4}"
STREAMING_PRESSURE_LINE_COUNT="${STREAMING_PRESSURE_LINE_COUNT:-4000}"
STREAMING_PRESSURE_MAX_TOKENS="${STREAMING_PRESSURE_MAX_TOKENS:-256}"
STREAMING_PRESSURE_TEMPERATURE="${STREAMING_PRESSURE_TEMPERATURE:-1.0}"
STREAMING_PRESSURE_TOP_P="${STREAMING_PRESSURE_TOP_P:-1.0}"
STREAMING_PRESSURE_THINKING_MODE="${STREAMING_PRESSURE_THINKING_MODE:-thinking}"
STREAMING_PRESSURE_TIMEOUT="${STREAMING_PRESSURE_TIMEOUT:-3600}"
STREAMING_PRESSURE_MAX_TTFT_SECONDS="${STREAMING_PRESSURE_MAX_TTFT_SECONDS:-300}"
STREAMING_PRESSURE_MAX_ELAPSED_SECONDS="${STREAMING_PRESSURE_MAX_ELAPSED_SECONDS:-1200}"

RUNTIME_STATS_INTERVAL_SECONDS="${RUNTIME_STATS_INTERVAL_SECONDS:-2}"
MTP_SPECULATIVE_CONFIG="${MTP_SPECULATIVE_CONFIG:-{\"method\":\"mtp\",\"num_speculative_tokens\":2}}"

if [[ -z "${B200_EXTRA_SERVE_ARGS+x}" ]]; then
  extra_args=(
    --data-parallel-size "${B200_DATA_PARALLEL_SIZE}"
    --gpu-memory-utilization "${SM12X_DP_EP_OOM_GPU_MEMORY_UTILIZATION}"
    --max-num-seqs "${SM12X_DP_EP_OOM_MAX_NUM_SEQS}"
    --max-num-batched-tokens "${SM12X_DP_EP_OOM_MAX_NUM_BATCHED_TOKENS}"
    --enable-prompt-tokens-details
    --default-chat-template-kwargs '{"thinking": true}'
    --compilation-config '{"cudagraph_mode":"FULL_AND_PIECEWISE","custom_ops":["all"]}'
  )
  if [[ "${SERVE_ENABLE_EXPERT_PARALLEL}" == "1" || "${SERVE_ENABLE_EXPERT_PARALLEL}" == "true" ]]; then
    extra_args+=(--enable-expert-parallel)
  fi
  if [[ "${SERVE_ENABLE_CHUNKED_PREFILL}" == "1" || "${SERVE_ENABLE_CHUNKED_PREFILL}" == "true" ]]; then
    extra_args+=(--enable-chunked-prefill)
  fi

  B200_EXTRA_SERVE_ARGS=""
  for arg in "${extra_args[@]}"; do
    B200_EXTRA_SERVE_ARGS+=" $(shell_quote "${arg}")"
  done
  B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS# }"
fi

export SM12X_DP_EP_OOM_LABEL SM12X_DP_EP_OOM_GPU_MEMORY_UTILIZATION
export SM12X_DP_EP_OOM_MAX_NUM_SEQS SM12X_DP_EP_OOM_MAX_NUM_BATCHED_TOKENS
export B200_BASELINE_LABEL B200_BASELINE_VARIANTS B200_BASELINE_PHASES
export B200_DATA_PARALLEL_SIZE B200_TENSOR_PARALLEL_SIZE
export B200_BLOCK_SIZE B200_KV_CACHE_DTYPE SERVE_MAX_MODEL_LEN
export SERVE_PREFIX_CACHE_MODE SERVE_ENABLE_EXPERT_PARALLEL
export SERVE_ENABLE_CHUNKED_PREFILL GPU_TOPOLOGY_SLUG
export RUN_PREFIX_CACHE_STRESS PREFIX_CACHE_STRESS_CASE_NAME
export PREFIX_CACHE_STRESS_TRIALS PREFIX_CACHE_STRESS_FILLER_WORDS
export PREFIX_CACHE_STRESS_TURNS PREFIX_CACHE_STRESS_MAX_TOKENS
export PREFIX_CACHE_STRESS_TEMPERATURE PREFIX_CACHE_STRESS_TOP_P
export PREFIX_CACHE_STRESS_TIMEOUT
export RUN_STREAMING_PRESSURE_SOAK STREAMING_PRESSURE_CASE_NAME
export STREAMING_PRESSURE_CONCURRENCY STREAMING_PRESSURE_ROUND_COUNT
export STREAMING_PRESSURE_LINE_COUNT STREAMING_PRESSURE_MAX_TOKENS
export STREAMING_PRESSURE_TEMPERATURE STREAMING_PRESSURE_TOP_P
export STREAMING_PRESSURE_THINKING_MODE STREAMING_PRESSURE_TIMEOUT
export STREAMING_PRESSURE_MAX_TTFT_SECONDS STREAMING_PRESSURE_MAX_ELAPSED_SECONDS
export RUNTIME_STATS_INTERVAL_SECONDS MTP_SPECULATIVE_CONFIG B200_EXTRA_SERVE_ARGS

"${SCRIPT_DIR}/run_b200_baseline.sh"
