#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

# External high-concurrency workspace-sizing gate.
# This mirrors a user-reported TP=4, MTP=2, prefix-cache-enabled, random
# 1K-input/1K-output C=256 workload that tripped locked workspace growth in
# DeepSeek V4 sparse MLA compressed decode. Keep it outside local SM120
# promotion gates: it targets four-card, high-concurrency throughput hosts.

SM120_WORKSPACE_SERVED_MODEL_NAME="${SM120_WORKSPACE_SERVED_MODEL_NAME:-DeepSeek-V4-Flash}"
SM120_WORKSPACE_CUDAGRAPH_MODE="${SM120_WORKSPACE_CUDAGRAPH_MODE:-FULL_AND_PIECEWISE}"
SM120_WORKSPACE_GPU_MEMORY_UTILIZATION="${SM120_WORKSPACE_GPU_MEMORY_UTILIZATION:-0.9}"
SM120_WORKSPACE_MAX_NUM_SEQS="${SM120_WORKSPACE_MAX_NUM_SEQS:-256}"
SM120_WORKSPACE_MAX_NUM_BATCHED_TOKENS="${SM120_WORKSPACE_MAX_NUM_BATCHED_TOKENS:-4096}"

B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-sm120_workspace_high_concurrency_c256_1k1k}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-bench_random_1024x1024_c256}"
RUN_RANDOM_1K1K_C256="${RUN_RANDOM_1K1K_C256:-1}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-4}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-140000}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-enabled}"
B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}"
B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-4x_sm12x_workspace_high_concurrency}"
RANDOM_1K1K_C256_INPUT_LEN="${RANDOM_1K1K_C256_INPUT_LEN:-1024}"
RANDOM_1K1K_C256_OUTPUT_LEN="${RANDOM_1K1K_C256_OUTPUT_LEN:-1024}"
RANDOM_1K1K_C256_CONCURRENCY="${RANDOM_1K1K_C256_CONCURRENCY:-256}"
RANDOM_1K1K_C256_NUM_PROMPTS="${RANDOM_1K1K_C256_NUM_PROMPTS:-1280}"
RANDOM_1K1K_C256_BENCH_TIMEOUT="${RANDOM_1K1K_C256_BENCH_TIMEOUT:-7200}"
BENCH_BACKEND="${BENCH_BACKEND:-openai-chat}"
BENCH_ENDPOINT="${BENCH_ENDPOINT:-/v1/chat/completions}"
VLLM_DEBUG_WORKSPACE="${VLLM_DEBUG_WORKSPACE:-1}"

if [[ -z "${B200_EXTRA_SERVE_ARGS+x}" ]]; then
  B200_EXTRA_SERVE_ARGS="--served-model-name ${SM120_WORKSPACE_SERVED_MODEL_NAME} --attention-backend FLASHMLA_SPARSE --gpu-memory-utilization ${SM120_WORKSPACE_GPU_MEMORY_UTILIZATION} --max-num-seqs ${SM120_WORKSPACE_MAX_NUM_SEQS} --max-num-batched-tokens ${SM120_WORKSPACE_MAX_NUM_BATCHED_TOKENS} --load-format auto --async-scheduling --enable-expert-parallel --compilation-config '{\"cudagraph_mode\":\"${SM120_WORKSPACE_CUDAGRAPH_MODE}\",\"custom_ops\":[\"all\"]}'"
fi

export SM120_WORKSPACE_SERVED_MODEL_NAME SM120_WORKSPACE_CUDAGRAPH_MODE
export SM120_WORKSPACE_GPU_MEMORY_UTILIZATION SM120_WORKSPACE_MAX_NUM_SEQS
export SM120_WORKSPACE_MAX_NUM_BATCHED_TOKENS
export B200_BASELINE_LABEL B200_BASELINE_VARIANTS B200_BASELINE_PHASES
export RUN_RANDOM_1K1K_C256 B200_TENSOR_PARALLEL_SIZE SERVE_MAX_MODEL_LEN
export SERVE_PREFIX_CACHE_MODE B200_BLOCK_SIZE B200_KV_CACHE_DTYPE
export GPU_TOPOLOGY_SLUG RANDOM_1K1K_C256_INPUT_LEN
export RANDOM_1K1K_C256_OUTPUT_LEN RANDOM_1K1K_C256_CONCURRENCY
export RANDOM_1K1K_C256_NUM_PROMPTS RANDOM_1K1K_C256_BENCH_TIMEOUT
export BENCH_BACKEND BENCH_ENDPOINT VLLM_DEBUG_WORKSPACE B200_EXTRA_SERVE_ARGS

"${SCRIPT_DIR}/run_b200_baseline.sh"
