#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-sm120_local_quality_gates}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-acceptance,long_context_probe,long_context_latency_matrix,long_context_mixed_arrival,streaming_pressure_matrix,bench_random_prefill_sweep,bench_hf_mt_bench,eval_gsm8k}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-131072}"
SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-disabled}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-2x_rtx_pro_6000_sm120}"
LONG_CONTEXT_LATENCY_CASE_NAME="${LONG_CONTEXT_LATENCY_CASE_NAME:-sm120_local_59k_124k_latency}"
LONG_CONTEXT_LATENCY_LINE_COUNTS="${LONG_CONTEXT_LATENCY_LINE_COUNTS:-1900,4000}"
LONG_CONTEXT_LATENCY_CONCURRENCY="${LONG_CONTEXT_LATENCY_CONCURRENCY:-1,2}"
LONG_CONTEXT_LATENCY_CACHE_MODES="${LONG_CONTEXT_LATENCY_CACHE_MODES:-cold}"
LONG_CONTEXT_LATENCY_REPEAT_COUNT="${LONG_CONTEXT_LATENCY_REPEAT_COUNT:-3}"
LONG_CONTEXT_LATENCY_MAX_TOKENS="${LONG_CONTEXT_LATENCY_MAX_TOKENS:-64}"
LONG_CONTEXT_LATENCY_PREWARM="${LONG_CONTEXT_LATENCY_PREWARM:-1}"
RUN_LONG_CONTEXT_MIXED_ARRIVAL="${RUN_LONG_CONTEXT_MIXED_ARRIVAL:-1}"
LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME:-sm120_local_mixed_long_short_arrival}"
LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS:-decode_then_59k:1900:1900:after_first_token:0:256:128,long_then_short:4000:192:fixed_delay:2:128:64}"
LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT="${LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT:-3}"
RUN_PREFIX_CACHE_PROBE="${RUN_PREFIX_CACHE_PROBE:-0}"
PREFIX_CACHE_CASE_NAME="${PREFIX_CACHE_CASE_NAME:-user_report_mtp1_prefix_cache_stability_proxy}"
PREFIX_CACHE_LINE_COUNT="${PREFIX_CACHE_LINE_COUNT:-384}"
PREFIX_CACHE_MAX_TOKENS="${PREFIX_CACHE_MAX_TOKENS:-64}"
PREFIX_CACHE_FAIL_ON_REGRESSION="${PREFIX_CACHE_FAIL_ON_REGRESSION:-1}"
RUN_STREAMING_PRESSURE_MATRIX="${RUN_STREAMING_PRESSURE_MATRIX:-1}"
STREAMING_PRESSURE_MATRIX_CASE_SPECS="${STREAMING_PRESSURE_MATRIX_CASE_SPECS:-short_c4:4:3:1200:128,issue7_5k_c4:4:3:192:128,long_c2:2:2:4000:128,long_c4:4:2:2400:128}"
RUN_RANDOM_PREFILL_SWEEP="${RUN_RANDOM_PREFILL_SWEEP:-1}"
RANDOM_PREFILL_INPUT_LENS="${RANDOM_PREFILL_INPUT_LENS:-1024,4096,16384,65536}"
RANDOM_PREFILL_OUTPUT_LEN="${RANDOM_PREFILL_OUTPUT_LEN:-1}"
RANDOM_PREFILL_CONCURRENCY="${RANDOM_PREFILL_CONCURRENCY:-1}"
RANDOM_PREFILL_NUM_PROMPTS="${RANDOM_PREFILL_NUM_PROMPTS:-8}"
LM_EVAL_NUM_FEWSHOT="${LM_EVAL_NUM_FEWSHOT:-5}"
LM_EVAL_LIMIT="${LM_EVAL_LIMIT:-50}"
MTP_LM_EVAL_NUM_CONCURRENT="${MTP_LM_EVAL_NUM_CONCURRENT:-4}"

export B200_BASELINE_LABEL B200_BASELINE_VARIANTS B200_BASELINE_PHASES
export B200_TENSOR_PARALLEL_SIZE SERVE_MAX_MODEL_LEN SERVE_USE_FP4_INDEXER_CACHE
export SERVE_PREFIX_CACHE_MODE GPU_TOPOLOGY_SLUG
export LONG_CONTEXT_LATENCY_CASE_NAME LONG_CONTEXT_LATENCY_LINE_COUNTS
export LONG_CONTEXT_LATENCY_CONCURRENCY LONG_CONTEXT_LATENCY_CACHE_MODES
export LONG_CONTEXT_LATENCY_REPEAT_COUNT LONG_CONTEXT_LATENCY_MAX_TOKENS
export LONG_CONTEXT_LATENCY_PREWARM
export RUN_LONG_CONTEXT_MIXED_ARRIVAL LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME
export LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS
export LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT
export RUN_PREFIX_CACHE_PROBE PREFIX_CACHE_CASE_NAME PREFIX_CACHE_LINE_COUNT
export PREFIX_CACHE_MAX_TOKENS PREFIX_CACHE_FAIL_ON_REGRESSION
export RUN_STREAMING_PRESSURE_MATRIX STREAMING_PRESSURE_MATRIX_CASE_SPECS
export RUN_RANDOM_PREFILL_SWEEP RANDOM_PREFILL_INPUT_LENS
export RANDOM_PREFILL_OUTPUT_LEN RANDOM_PREFILL_CONCURRENCY
export RANDOM_PREFILL_NUM_PROMPTS
export LM_EVAL_NUM_FEWSHOT LM_EVAL_LIMIT MTP_LM_EVAL_NUM_CONCURRENT

"${SCRIPT_DIR}/run_b200_baseline.sh"
