#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

MODEL="${MODEL:-deepseek-ai/DeepSeek-V4-Flash-0731}"
ISSUE15_LABEL="${ISSUE15_LABEL:-sm120_issue15_fused_moe_startup}"
ISSUE15_VARIANTS="${ISSUE15_VARIANTS:-mtp}"
ISSUE15_TENSOR_PARALLEL_SIZE="${ISSUE15_TENSOR_PARALLEL_SIZE:-2}"
ISSUE15_MAX_MODEL_LEN="${ISSUE15_MAX_MODEL_LEN:-8192}"
ISSUE15_GPU_MEMORY_UTILIZATION="${ISSUE15_GPU_MEMORY_UTILIZATION:-0.90}"
ISSUE15_MAX_NUM_SEQS="${ISSUE15_MAX_NUM_SEQS:-8}"
ISSUE15_MAX_NUM_BATCHED_TOKENS="${ISSUE15_MAX_NUM_BATCHED_TOKENS:-4096}"
ISSUE15_SERVER_STARTUP_TIMEOUT="${ISSUE15_SERVER_STARTUP_TIMEOUT:-900}"
ISSUE15_SERVER_STARTUP_INTERVAL_SECONDS="${ISSUE15_SERVER_STARTUP_INTERVAL_SECONDS:-15}"
ISSUE15_PORT="${ISSUE15_PORT:-8092}"

ISSUE15_EXTRA_SERVE_ARGS="${ISSUE15_EXTRA_SERVE_ARGS:---gpu-memory-utilization ${ISSUE15_GPU_MEMORY_UTILIZATION} --max-num-seqs ${ISSUE15_MAX_NUM_SEQS} --max-num-batched-tokens ${ISSUE15_MAX_NUM_BATCHED_TOKENS} --enable-chunked-prefill --compilation-config '{\"cudagraph_mode\":\"FULL_AND_PIECEWISE\",\"custom_ops\":[\"all\"]}' --default-chat-template-kwargs '{\"thinking\": true}'}"

B200_BASELINE_LABEL="${ISSUE15_LABEL}" \
B200_BASELINE_VARIANTS="${ISSUE15_VARIANTS}" \
B200_BASELINE_PHASES=external_command \
RUN_EXTERNAL_COMMAND=1 \
EXTERNAL_COMMAND=true \
EXTERNAL_COMMAND_LABEL=issue15_fused_moe_model_load_smoke \
MODEL="${MODEL}" \
PORT="${ISSUE15_PORT}" \
SERVE_MAX_MODEL_LEN="${ISSUE15_MAX_MODEL_LEN}" \
B200_TENSOR_PARALLEL_SIZE="${ISSUE15_TENSOR_PARALLEL_SIZE}" \
B200_KV_CACHE_DTYPE=fp8 \
B200_BLOCK_SIZE=256 \
SERVE_PREFIX_CACHE_MODE=disabled \
B200_EXTRA_SERVE_ARGS="${ISSUE15_EXTRA_SERVE_ARGS}" \
SERVER_STARTUP_TIMEOUT="${ISSUE15_SERVER_STARTUP_TIMEOUT}" \
SERVER_STARTUP_INTERVAL_SECONDS="${ISSUE15_SERVER_STARTUP_INTERVAL_SECONDS}" \
exec "${SCRIPT_DIR}/run_b200_baseline.sh"
