#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

BASE_URL="${BASE_URL:-http://127.0.0.1:8000}"
MODEL="${MODEL:-deepseek-ai/DeepSeek-V4-Flash}"
PYTHON="${PYTHON:-python}"
STREAMING_PRESSURE_MATRIX_VARIANT="${STREAMING_PRESSURE_MATRIX_VARIANT:-manual}"
STREAMING_PRESSURE_MATRIX_CASE_NAME="${STREAMING_PRESSURE_MATRIX_CASE_NAME:-streaming_pressure_continuous_matrix}"
STREAMING_PRESSURE_MATRIX_CASE_SPECS="${STREAMING_PRESSURE_MATRIX_CASE_SPECS:-short_c4:4:3:1200:128,long_c2:2:2:4000:128,long_c4:4:2:2400:128}"
STREAMING_PRESSURE_MATRIX_TEMPERATURE="${STREAMING_PRESSURE_MATRIX_TEMPERATURE:-1.0}"
STREAMING_PRESSURE_MATRIX_TOP_P="${STREAMING_PRESSURE_MATRIX_TOP_P:-1.0}"
STREAMING_PRESSURE_MATRIX_THINKING_MODE="${STREAMING_PRESSURE_MATRIX_THINKING_MODE:-non-thinking}"
STREAMING_PRESSURE_MATRIX_TIMEOUT="${STREAMING_PRESSURE_MATRIX_TIMEOUT:-1800}"
STREAMING_PRESSURE_MATRIX_REQUEST_RETRIES="${STREAMING_PRESSURE_MATRIX_REQUEST_RETRIES:-${API_REQUEST_RETRIES:-1}}"
STREAMING_PRESSURE_MATRIX_MAX_TTFT_SECONDS="${STREAMING_PRESSURE_MATRIX_MAX_TTFT_SECONDS:-120}"
STREAMING_PRESSURE_MATRIX_MAX_ELAPSED_SECONDS="${STREAMING_PRESSURE_MATRIX_MAX_ELAPSED_SECONDS:-900}"
STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW="${STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW:-0}"
SERVE_LOG="${SERVE_LOG:-}"
SERVER_GUARD="${SERVER_GUARD:-1}"
SERVER_STARTUP_TIMEOUT="${SERVER_STARTUP_TIMEOUT:-1800}"
SERVER_STARTUP_INTERVAL_SECONDS="${SERVER_STARTUP_INTERVAL_SECONDS:-15}"
SERVER_HEALTH_TIMEOUT="${SERVER_HEALTH_TIMEOUT:-10}"
SERVER_FAILURE_GRACE_TIMEOUT="${SERVER_FAILURE_GRACE_TIMEOUT:-300}"
SERVER_FAILURE_GRACE_INTERVAL_SECONDS="${SERVER_FAILURE_GRACE_INTERVAL_SECONDS:-10}"
SERVER_RECOVERY_CMD="${SERVER_RECOVERY_CMD:-}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-${REPO_ROOT}/artifacts}"
RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y%m%d%H%M%S)}"
BRANCH_NAME="${BRANCH_NAME:-$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown-branch)}"
BRANCH_SLUG="$(printf '%s' "${BRANCH_NAME}" | sed -E 's#[/[:space:]]+#_#g; s#[^A-Za-z0-9_.-]#_#g')"
BRANCH_SLUG="${BRANCH_SLUG:-unknown-branch}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-$(detect_gpu_topology_slug)}"
OUT_DIR="${OUT_DIR:-${ARTIFACT_ROOT}/${BRANCH_SLUG}/${GPU_TOPOLOGY_SLUG}/streaming_pressure_matrix/${RUN_TIMESTAMP}}"
export BASE_URL MODEL PYTHON STREAMING_PRESSURE_MATRIX_VARIANT
export STREAMING_PRESSURE_MATRIX_CASE_NAME STREAMING_PRESSURE_MATRIX_CASE_SPECS
export STREAMING_PRESSURE_MATRIX_TEMPERATURE STREAMING_PRESSURE_MATRIX_TOP_P
export STREAMING_PRESSURE_MATRIX_THINKING_MODE STREAMING_PRESSURE_MATRIX_TIMEOUT
export STREAMING_PRESSURE_MATRIX_REQUEST_RETRIES
export STREAMING_PRESSURE_MATRIX_MAX_TTFT_SECONDS
export STREAMING_PRESSURE_MATRIX_MAX_ELAPSED_SECONDS
export STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW
export SERVE_LOG SERVER_GUARD SERVER_STARTUP_TIMEOUT
export SERVER_STARTUP_INTERVAL_SECONDS SERVER_HEALTH_TIMEOUT
export SERVER_FAILURE_GRACE_TIMEOUT SERVER_FAILURE_GRACE_INTERVAL_SECONDS
export SERVER_RECOVERY_CMD ARTIFACT_ROOT RUN_TIMESTAMP BRANCH_NAME GPU_TOPOLOGY_SLUG OUT_DIR

mkdir -p "${OUT_DIR}"
write_run_environment
source "${SCRIPT_DIR}/vllm_collect_env.sh"
collect_vllm_env
source "${SCRIPT_DIR}/gpu_stats.sh"
source "${SCRIPT_DIR}/runtime_stats.sh"
start_gpu_stats
start_runtime_stats
trap 'stop_runtime_stats; stop_gpu_stats' EXIT

if ! wait_for_server_ready "${SERVER_STARTUP_TIMEOUT}" "${SERVER_STARTUP_INTERVAL_SECONDS}" "server startup before streaming-pressure matrix"; then
  printf '%s\n' "124" > "${OUT_DIR}/streaming_pressure_matrix.exit_code"
  mark_server_unresponsive "streaming_pressure_matrix" "server not ready after startup wait"
  echo "wrote ${OUT_DIR}"
  exit 1
fi

slow_args=()
if [[ "${STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW}" == "1" || "${STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW}" == "true" ]]; then
  slow_args+=(--fail-on-slow)
fi

set +e
"${PYTHON}" -m ds4_harness.cli streaming-pressure-matrix \
  --base-url "${BASE_URL}" \
  --model "${MODEL}" \
  --variant "${STREAMING_PRESSURE_MATRIX_VARIANT}" \
  --case-name "${STREAMING_PRESSURE_MATRIX_CASE_NAME}" \
  --case-specs "${STREAMING_PRESSURE_MATRIX_CASE_SPECS}" \
  --temperature "${STREAMING_PRESSURE_MATRIX_TEMPERATURE}" \
  --top-p "${STREAMING_PRESSURE_MATRIX_TOP_P}" \
  --thinking-mode "${STREAMING_PRESSURE_MATRIX_THINKING_MODE}" \
  --timeout "${STREAMING_PRESSURE_MATRIX_TIMEOUT}" \
  --request-retries "${STREAMING_PRESSURE_MATRIX_REQUEST_RETRIES}" \
  --max-ttft-seconds "${STREAMING_PRESSURE_MATRIX_MAX_TTFT_SECONDS}" \
  --max-elapsed-seconds "${STREAMING_PRESSURE_MATRIX_MAX_ELAPSED_SECONDS}" \
  ${slow_args[@]+"${slow_args[@]}"} \
  --json-output "${OUT_DIR}/streaming_pressure_matrix.json" \
  --markdown-output "${OUT_DIR}/streaming_pressure_matrix.md"
code="$?"
set -e
printf '%s\n' "${code}" > "${OUT_DIR}/streaming_pressure_matrix.exit_code"
if [[ "${code}" != "0" ]] && ! wait_for_server_ready "${SERVER_FAILURE_GRACE_TIMEOUT}" "${SERVER_FAILURE_GRACE_INTERVAL_SECONDS}" "server after streaming-pressure matrix"; then
  mark_server_unresponsive "streaming_pressure_matrix" "server unresponsive after streaming-pressure matrix"
fi

echo "wrote ${OUT_DIR}"
exit "${code}"
