#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

MODEL="${MODEL:-deepseek-ai/DeepSeek-V4-Flash}"
HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-8080}"
B200_VLLM_REPO="${B200_VLLM_REPO:-/workspace/vllm}"
B200_VLLM_VENV="${B200_VLLM_VENV:-${B200_VLLM_REPO}/.venv}"
PYTHON="${PYTHON:-${B200_VLLM_VENV}/bin/python}"
VLLM_BIN="${VLLM_BIN:-${B200_VLLM_VENV}/bin/vllm}"
RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y%m%d%H%M%S)}"
BRANCH_NAME="${BRANCH_NAME:-$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown-branch)}"
BRANCH_SLUG="$(printf '%s' "${BRANCH_NAME}" | sed -E 's#[/[:space:]]+#_#g; s#[^A-Za-z0-9_.-]#_#g')"
BRANCH_SLUG="${BRANCH_SLUG:-unknown-branch}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-$(detect_gpu_topology_slug)}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-${REPO_ROOT}/artifacts}"
USER_FEEDBACK_MATRIX_LABEL="${USER_FEEDBACK_MATRIX_LABEL:-sm120_user_feedback_matrix}"
USER_FEEDBACK_MATRIX_ROOT="${OUT_DIR:-${ARTIFACT_ROOT}/${BRANCH_SLUG}/${GPU_TOPOLOGY_SLUG}/${USER_FEEDBACK_MATRIX_LABEL}/${RUN_TIMESTAMP}}"

RUN_USER_FEEDBACK_PRIMARY="${RUN_USER_FEEDBACK_PRIMARY:-1}"
RUN_USER_FEEDBACK_PREFIX_CACHE="${RUN_USER_FEEDBACK_PREFIX_CACHE:-1}"
RUN_USER_FEEDBACK_KV_LIFECYCLE="${RUN_USER_FEEDBACK_KV_LIFECYCLE:-1}"
RUN_USER_FEEDBACK_ISSUE10="${RUN_USER_FEEDBACK_ISSUE10:-0}"
RUN_USER_FEEDBACK_SUMMARY="${RUN_USER_FEEDBACK_SUMMARY:-1}"

USER_FEEDBACK_PRIMARY_OUT_DIR="${USER_FEEDBACK_PRIMARY_OUT_DIR:-${USER_FEEDBACK_MATRIX_ROOT}/primary}"
USER_FEEDBACK_PREFIX_CACHE_OUT_DIR="${USER_FEEDBACK_PREFIX_CACHE_OUT_DIR:-${USER_FEEDBACK_MATRIX_ROOT}/prefix_cache}"
USER_FEEDBACK_KV_LIFECYCLE_OUT_DIR="${USER_FEEDBACK_KV_LIFECYCLE_OUT_DIR:-${USER_FEEDBACK_MATRIX_ROOT}/kv_lifecycle_prefix_cache}"
USER_FEEDBACK_ISSUE10_OUT_DIR="${USER_FEEDBACK_ISSUE10_OUT_DIR:-${USER_FEEDBACK_MATRIX_ROOT}/issue10}"
USER_FEEDBACK_PRIMARY_LABEL="${USER_FEEDBACK_PRIMARY_LABEL:-${USER_FEEDBACK_MATRIX_LABEL}_primary}"
USER_FEEDBACK_PREFIX_CACHE_LABEL="${USER_FEEDBACK_PREFIX_CACHE_LABEL:-${USER_FEEDBACK_MATRIX_LABEL}_prefix_cache}"
USER_FEEDBACK_KV_LIFECYCLE_LABEL="${USER_FEEDBACK_KV_LIFECYCLE_LABEL:-${USER_FEEDBACK_MATRIX_LABEL}_kv_lifecycle_prefix_cache}"
USER_FEEDBACK_ISSUE10_LABEL="${USER_FEEDBACK_ISSUE10_LABEL:-${USER_FEEDBACK_MATRIX_LABEL}_issue10}"

# Dual RTX PRO 6000 128K small-concurrency default. The measured 0.975 /
# max_num_seqs=4 shape leaves enough KV cache for 124K/128K prompts while
# avoiding the startup OOM seen when graph capture scales to larger batches.
USER_FEEDBACK_GPU_MEMORY_UTILIZATION="${USER_FEEDBACK_GPU_MEMORY_UTILIZATION:-0.975}"
USER_FEEDBACK_MAX_NUM_BATCHED_TOKENS="${USER_FEEDBACK_MAX_NUM_BATCHED_TOKENS:-4096}"
USER_FEEDBACK_MAX_NUM_SEQS="${USER_FEEDBACK_MAX_NUM_SEQS:-4}"
_DEFAULT_USER_FEEDBACK_EXTRA_SERVE_ARGS="--gpu-memory-utilization ${USER_FEEDBACK_GPU_MEMORY_UTILIZATION} --max-num-batched-tokens ${USER_FEEDBACK_MAX_NUM_BATCHED_TOKENS} --max-num-seqs ${USER_FEEDBACK_MAX_NUM_SEQS} --enable-expert-parallel --compilation-config '{\"cudagraph_mode\":\"FULL_AND_PIECEWISE\",\"custom_ops\":[\"all\"]}'"
B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS:-${_DEFAULT_USER_FEEDBACK_EXTRA_SERVE_ARGS}}"

mkdir -p "${USER_FEEDBACK_MATRIX_ROOT}"

failures=0
run_child() {
  local child_out="$1"
  shift

  mkdir -p "${child_out}"
  set +e
  "$@" >"${child_out}/child.stdout.log" 2>"${child_out}/child.stderr.log"
  local code="$?"
  set -e
  if [[ "${code}" != "0" ]]; then
    failures=1
  fi
}

if [[ "${RUN_USER_FEEDBACK_PRIMARY}" == "1" || "${RUN_USER_FEEDBACK_PRIMARY}" == "true" ]]; then
  run_child "${USER_FEEDBACK_PRIMARY_OUT_DIR}" env \
    OUT_DIR="${USER_FEEDBACK_PRIMARY_OUT_DIR}" \
    MODEL="${MODEL}" HOST="${HOST}" PORT="${PORT}" \
    B200_VLLM_REPO="${B200_VLLM_REPO}" B200_VLLM_VENV="${B200_VLLM_VENV}" \
    PYTHON="${PYTHON}" VLLM_BIN="${VLLM_BIN}" \
    B200_BASELINE_LABEL="${USER_FEEDBACK_PRIMARY_LABEL}" \
    ARTIFACT_ARCHIVE_PREVIOUS=0 \
    B200_BASELINE_VARIANTS="${USER_FEEDBACK_PRIMARY_VARIANTS:-mtp}" \
    B200_BASELINE_PHASES="${USER_FEEDBACK_PRIMARY_PHASES:-long_context_latency_matrix,frontier_context_sweep,ds4_story_recall_semantic,long_context_decode_concurrency,long_context_mixed_arrival,kv_lifecycle_probe,streaming_pressure_matrix,bench_hf_mt_bench,eval_gsm8k,bench_random_prefill_sweep,bench_random_8000x1000,bench_random_256x256}" \
    B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}" \
    B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}" \
    B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}" \
    SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-131072}" \
    SERVE_PREFIX_CACHE_MODE="${USER_FEEDBACK_PRIMARY_PREFIX_CACHE_MODE:-disabled}" \
    SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}" \
    B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS}" \
    LONG_CONTEXT_LATENCY_CASE_NAME="${LONG_CONTEXT_LATENCY_CASE_NAME:-user_feedback_59k_124k_latency}" \
    LONG_CONTEXT_LATENCY_LINE_COUNTS="${LONG_CONTEXT_LATENCY_LINE_COUNTS:-1900,4000}" \
    LONG_CONTEXT_LATENCY_CONCURRENCY="${LONG_CONTEXT_LATENCY_CONCURRENCY:-1,2}" \
    LONG_CONTEXT_LATENCY_CACHE_MODES="${LONG_CONTEXT_LATENCY_CACHE_MODES:-cold}" \
    LONG_CONTEXT_LATENCY_REPEAT_COUNT="${LONG_CONTEXT_LATENCY_REPEAT_COUNT:-3}" \
    LONG_CONTEXT_LATENCY_MAX_TOKENS="${LONG_CONTEXT_LATENCY_MAX_TOKENS:-64}" \
    LONG_CONTEXT_LATENCY_PREWARM="${LONG_CONTEXT_LATENCY_PREWARM:-1}" \
    RUN_FRONTIER_CONTEXT_SWEEP="${RUN_FRONTIER_CONTEXT_SWEEP:-1}" \
    FRONTIER_CONTEXT_SWEEP_CASE_NAME="${FRONTIER_CONTEXT_SWEEP_CASE_NAME:-user_feedback_frontier_context_sweep}" \
    FRONTIER_CONTEXT_SWEEP_PROMPT_FILES="${FRONTIER_CONTEXT_SWEEP_PROMPT_FILES:-${REPO_ROOT}/prompts/long_context/ds4_story_recall.txt,${REPO_ROOT}/prompts/long_context/ds4_security_audit.txt}" \
    FRONTIER_CONTEXT_SWEEP_FRONTIERS="${FRONTIER_CONTEXT_SWEEP_FRONTIERS:-8192,16384,32768,65536,98304,124000}" \
    FRONTIER_CONTEXT_SWEEP_REPEAT_COUNT="${FRONTIER_CONTEXT_SWEEP_REPEAT_COUNT:-1}" \
    FRONTIER_CONTEXT_SWEEP_MAX_TOKENS="${FRONTIER_CONTEXT_SWEEP_MAX_TOKENS:-128}" \
    FRONTIER_CONTEXT_SWEEP_PREWARM="${FRONTIER_CONTEXT_SWEEP_PREWARM:-1}" \
    RUN_DS4_STORY_RECALL_SEMANTIC="${RUN_DS4_STORY_RECALL_SEMANTIC:-1}" \
    DS4_STORY_RECALL_CASE_NAME="${DS4_STORY_RECALL_CASE_NAME:-user_feedback_ds4_story_recall_semantic}" \
    DS4_STORY_RECALL_PROMPT_FILE="${DS4_STORY_RECALL_PROMPT_FILE:-${REPO_ROOT}/prompts/long_context/ds4_story_recall.txt}" \
    DS4_STORY_RECALL_MAX_TOKENS="${DS4_STORY_RECALL_MAX_TOKENS:-128}" \
    RUN_LONG_CONTEXT_DECODE_CONCURRENCY="${RUN_LONG_CONTEXT_DECODE_CONCURRENCY:-1}" \
    LONG_CONTEXT_DECODE_CASE_NAME="${LONG_CONTEXT_DECODE_CASE_NAME:-user_feedback_124k_decode_concurrency}" \
    LONG_CONTEXT_DECODE_LINE_COUNTS="${LONG_CONTEXT_DECODE_LINE_COUNTS:-4000}" \
    LONG_CONTEXT_DECODE_CONCURRENCY="${LONG_CONTEXT_DECODE_CONCURRENCY:-1,2}" \
    LONG_CONTEXT_DECODE_CACHE_MODES="${LONG_CONTEXT_DECODE_CACHE_MODES:-cold}" \
    LONG_CONTEXT_DECODE_REPEAT_COUNT="${LONG_CONTEXT_DECODE_REPEAT_COUNT:-1}" \
    LONG_CONTEXT_DECODE_MAX_TOKENS="${LONG_CONTEXT_DECODE_MAX_TOKENS:-256}" \
    RUN_LONG_CONTEXT_MIXED_ARRIVAL="${RUN_LONG_CONTEXT_MIXED_ARRIVAL:-1}" \
    LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME:-user_feedback_mixed_arrival}" \
    LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS:-decode_then_59k:1900:1900:after_first_token:0:256:128,decode_then_124k:4000:4000:after_first_token:0:256:128,long_then_short:4000:192:fixed_delay:2:128:64}" \
    LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT="${LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT:-3}" \
    RUN_KV_LIFECYCLE_PROBE="${RUN_KV_LIFECYCLE_PROBE:-1}" \
    KV_LIFECYCLE_CASE_NAME="${KV_LIFECYCLE_CASE_NAME:-user_feedback_prefix_disabled_idle_kv_lifecycle}" \
    KV_LIFECYCLE_CACHE_MODE="${KV_LIFECYCLE_CACHE_MODE:-disabled}" \
    KV_LIFECYCLE_SESSION_COUNT="${KV_LIFECYCLE_SESSION_COUNT:-2}" \
    KV_LIFECYCLE_LINE_COUNT="${KV_LIFECYCLE_LINE_COUNT:-1900}" \
    KV_LIFECYCLE_MAX_TOKENS="${KV_LIFECYCLE_MAX_TOKENS:-64}" \
    KV_LIFECYCLE_MAX_IDLE_KV_PERCENT="${KV_LIFECYCLE_MAX_IDLE_KV_PERCENT:-2.0}" \
    KV_LIFECYCLE_INCLUDE_ABORT="${KV_LIFECYCLE_INCLUDE_ABORT:-1}" \
    RUN_STREAMING_PRESSURE_MATRIX="${RUN_STREAMING_PRESSURE_MATRIX:-1}" \
    STREAMING_PRESSURE_MATRIX_CASE_SPECS="${STREAMING_PRESSURE_MATRIX_CASE_SPECS:-short_c4:4:3:1200:128,issue7_5k_c4:4:3:192:128,long_c2:2:2:4000:128,long_c4:4:2:2400:128}" \
    RUN_RANDOM_PREFILL_SWEEP="${RUN_RANDOM_PREFILL_SWEEP:-1}" \
    RANDOM_PREFILL_INPUT_LENS="${RANDOM_PREFILL_INPUT_LENS:-1024,4096,16384,65536}" \
    RANDOM_PREFILL_OUTPUT_LEN="${RANDOM_PREFILL_OUTPUT_LEN:-1}" \
    RANDOM_PREFILL_CONCURRENCY="${RANDOM_PREFILL_CONCURRENCY:-1}" \
    RANDOM_PREFILL_NUM_PROMPTS="${RANDOM_PREFILL_NUM_PROMPTS:-8}" \
    RUN_RANDOM_8K1K="${RUN_RANDOM_8K1K:-1}" \
    RANDOM_8K1K_INPUT_LEN="${RANDOM_8K1K_INPUT_LEN:-8000}" \
    RANDOM_8K1K_OUTPUT_LEN="${RANDOM_8K1K_OUTPUT_LEN:-1000}" \
    RANDOM_8K1K_CONCURRENCY="${RANDOM_8K1K_CONCURRENCY:-1,2,4,8,16,32}" \
    RANDOM_8K1K_NUM_PROMPTS="${RANDOM_8K1K_NUM_PROMPTS:-80}" \
    RUN_RANDOM_256X256="${RUN_RANDOM_256X256:-1}" \
    RANDOM_256X256_INPUT_LEN="${RANDOM_256X256_INPUT_LEN:-256}" \
    RANDOM_256X256_OUTPUT_LEN="${RANDOM_256X256_OUTPUT_LEN:-256}" \
    RANDOM_256X256_CONCURRENCY="${RANDOM_256X256_CONCURRENCY:-1,4,16}" \
    RANDOM_256X256_NUM_PROMPTS="${RANDOM_256X256_NUM_PROMPTS:-80}" \
    NUM_PROMPTS="${NUM_PROMPTS:-80}" \
    MTP_CONCURRENCY="${MTP_CONCURRENCY:-1,2,4,8,16,24}" \
    LM_EVAL_NUM_FEWSHOT="${LM_EVAL_NUM_FEWSHOT:-5}" \
    LM_EVAL_LIMIT="${LM_EVAL_LIMIT:-200}" \
    MTP_LM_EVAL_NUM_CONCURRENT="${MTP_LM_EVAL_NUM_CONCURRENT:-4}" \
    LM_EVAL_GATE_FLOORS="${LM_EVAL_GATE_FLOORS:-exact_match_flexible=0.94,exact_match_strict=0.925}" \
    "${SCRIPT_DIR}/run_b200_baseline.sh"
fi

if [[ "${RUN_USER_FEEDBACK_PREFIX_CACHE}" == "1" || "${RUN_USER_FEEDBACK_PREFIX_CACHE}" == "true" ]]; then
  run_child "${USER_FEEDBACK_PREFIX_CACHE_OUT_DIR}" env \
    OUT_DIR="${USER_FEEDBACK_PREFIX_CACHE_OUT_DIR}" \
    MODEL="${MODEL}" HOST="${HOST}" PORT="$((PORT + 1))" \
    B200_VLLM_REPO="${B200_VLLM_REPO}" B200_VLLM_VENV="${B200_VLLM_VENV}" \
    PYTHON="${PYTHON}" VLLM_BIN="${VLLM_BIN}" \
    B200_BASELINE_LABEL="${USER_FEEDBACK_PREFIX_CACHE_LABEL}" \
    ARTIFACT_ARCHIVE_PREVIOUS=0 \
    B200_BASELINE_VARIANTS="${USER_FEEDBACK_PREFIX_CACHE_VARIANTS:-mtp1}" \
    B200_BASELINE_PHASES="${USER_FEEDBACK_PREFIX_CACHE_PHASES:-prefix_cache_stress}" \
    B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}" \
    B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}" \
    B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}" \
    SERVE_MAX_MODEL_LEN="${USER_FEEDBACK_PREFIX_CACHE_MAX_MODEL_LEN:-16384}" \
    SERVE_PREFIX_CACHE_MODE="${USER_FEEDBACK_PREFIX_CACHE_MODE:-enabled}" \
    SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}" \
    B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS}" \
    PREFIX_CACHE_DIAGNOSTIC_CASES="${PREFIX_CACHE_DIAGNOSTIC_CASES:-default}" \
    RUN_PREFIX_CACHE_STRESS="${RUN_PREFIX_CACHE_STRESS:-1}" \
    PREFIX_CACHE_STRESS_CASE_NAME="${PREFIX_CACHE_STRESS_CASE_NAME:-user_feedback_prefix_cache_http_metrics_stress}" \
    PREFIX_CACHE_STRESS_TRIALS="${PREFIX_CACHE_STRESS_TRIALS:-5}" \
    PREFIX_CACHE_STRESS_FILLER_WORDS="${PREFIX_CACHE_STRESS_FILLER_WORDS:-800}" \
    PREFIX_CACHE_STRESS_FILLER_WORDS_LIST="${PREFIX_CACHE_STRESS_FILLER_WORDS_LIST:-100,400,800,1600,3200}" \
    PREFIX_CACHE_STRESS_TURNS="${PREFIX_CACHE_STRESS_TURNS:-3}" \
    PREFIX_CACHE_STRESS_MAX_TOKENS="${PREFIX_CACHE_STRESS_MAX_TOKENS:-256}" \
    "${SCRIPT_DIR}/run_sm120_mtp1_prefix_cache_diagnostics.sh"
fi

if [[ "${RUN_USER_FEEDBACK_KV_LIFECYCLE}" == "1" || "${RUN_USER_FEEDBACK_KV_LIFECYCLE}" == "true" ]]; then
  run_child "${USER_FEEDBACK_KV_LIFECYCLE_OUT_DIR}" env \
    OUT_DIR="${USER_FEEDBACK_KV_LIFECYCLE_OUT_DIR}" \
    MODEL="${MODEL}" HOST="${HOST}" PORT="$((PORT + 3))" \
    B200_VLLM_REPO="${B200_VLLM_REPO}" B200_VLLM_VENV="${B200_VLLM_VENV}" \
    PYTHON="${PYTHON}" VLLM_BIN="${VLLM_BIN}" \
    B200_BASELINE_LABEL="${USER_FEEDBACK_KV_LIFECYCLE_LABEL}" \
    ARTIFACT_ARCHIVE_PREVIOUS=0 \
    B200_BASELINE_VARIANTS="${USER_FEEDBACK_KV_LIFECYCLE_VARIANTS:-mtp}" \
    B200_BASELINE_PHASES="${USER_FEEDBACK_KV_LIFECYCLE_PHASES:-kv_lifecycle_probe}" \
    B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}" \
    B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}" \
    B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}" \
    SERVE_MAX_MODEL_LEN="${USER_FEEDBACK_KV_LIFECYCLE_MAX_MODEL_LEN:-131072}" \
    SERVE_PREFIX_CACHE_MODE="enabled" \
    SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}" \
    B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS}" \
    RUN_KV_LIFECYCLE_PROBE=1 \
    KV_LIFECYCLE_CASE_NAME="${USER_FEEDBACK_KV_LIFECYCLE_CASE_NAME:-user_feedback_prefix_enabled_kv_recoverability}" \
    KV_LIFECYCLE_CACHE_MODE="enabled" \
    KV_LIFECYCLE_SESSION_COUNT="${USER_FEEDBACK_KV_LIFECYCLE_SESSION_COUNT:-3}" \
    KV_LIFECYCLE_LINE_COUNT="${USER_FEEDBACK_KV_LIFECYCLE_LINE_COUNT:-1900}" \
    KV_LIFECYCLE_MAX_TOKENS="${USER_FEEDBACK_KV_LIFECYCLE_MAX_TOKENS:-64}" \
    KV_LIFECYCLE_MAX_IDLE_KV_PERCENT="${USER_FEEDBACK_KV_LIFECYCLE_MAX_IDLE_KV_PERCENT:-90.0}" \
    KV_LIFECYCLE_INCLUDE_ABORT="${USER_FEEDBACK_KV_LIFECYCLE_INCLUDE_ABORT:-1}" \
    "${SCRIPT_DIR}/run_b200_baseline.sh"
fi

if [[ "${RUN_USER_FEEDBACK_ISSUE10}" == "1" || "${RUN_USER_FEEDBACK_ISSUE10}" == "true" ]]; then
  run_child "${USER_FEEDBACK_ISSUE10_OUT_DIR}" env \
    OUT_DIR="${USER_FEEDBACK_ISSUE10_OUT_DIR}" \
    MODEL="${MODEL}" HOST="${HOST}" PORT="$((PORT + 2))" \
    B200_VLLM_REPO="${B200_VLLM_REPO}" B200_VLLM_VENV="${B200_VLLM_VENV}" \
    PYTHON="${PYTHON}" VLLM_BIN="${VLLM_BIN}" \
    B200_BASELINE_LABEL="${USER_FEEDBACK_ISSUE10_LABEL}" \
    ARTIFACT_ARCHIVE_PREVIOUS=0 \
    SERVE_MAX_MODEL_LEN="${USER_FEEDBACK_ISSUE10_MAX_MODEL_LEN:-65536}" \
    ISSUE10_ALLOW_HOST_REBOOT_RISK="${ISSUE10_ALLOW_HOST_REBOOT_RISK:-0}" \
    "${SCRIPT_DIR}/run_sm120_issue10_startup_gate.sh"
fi

if [[ "${RUN_USER_FEEDBACK_SUMMARY}" == "1" || "${RUN_USER_FEEDBACK_SUMMARY}" == "true" ]]; then
  summary_args=()
  if [[ -d "${USER_FEEDBACK_PRIMARY_OUT_DIR}" ]]; then
    summary_args+=(--run "primary=${USER_FEEDBACK_PRIMARY_OUT_DIR}")
  fi
  if [[ -d "${USER_FEEDBACK_PREFIX_CACHE_OUT_DIR}" ]]; then
    summary_args+=(--run "prefix_cache=${USER_FEEDBACK_PREFIX_CACHE_OUT_DIR}")
  fi
  if [[ -d "${USER_FEEDBACK_KV_LIFECYCLE_OUT_DIR}" ]]; then
    summary_args+=(--run "kv_lifecycle=${USER_FEEDBACK_KV_LIFECYCLE_OUT_DIR}")
  fi
  if [[ -d "${USER_FEEDBACK_ISSUE10_OUT_DIR}" ]]; then
    summary_args+=(--run "issue10=${USER_FEEDBACK_ISSUE10_OUT_DIR}")
  fi
  if [[ "${#summary_args[@]}" -gt 0 ]]; then
    set +e
    "${PYTHON}" "${SCRIPT_DIR}/summarize_sm120_user_feedback_matrix.py" \
      "${summary_args[@]}" \
      --json-output "${USER_FEEDBACK_MATRIX_ROOT}/user_feedback_matrix_summary.json" \
      --markdown-output "${USER_FEEDBACK_MATRIX_ROOT}/user_feedback_matrix_summary.md" \
      >"${USER_FEEDBACK_MATRIX_ROOT}/summary.stdout.log" \
      2>"${USER_FEEDBACK_MATRIX_ROOT}/summary.stderr.log"
    summary_code="$?"
    set -e
    if [[ "${summary_code}" != "0" ]]; then
      failures=1
    fi
  fi
fi

echo "wrote ${USER_FEEDBACK_MATRIX_ROOT}"
exit "${failures}"
