#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-sm120_mtp1_prefix_cache_stability}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp1}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-prefix_cache_stress}"
RUN_PREFIX_CACHE_STRESS="${RUN_PREFIX_CACHE_STRESS:-1}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}"
B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}"
B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-16384}"
SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-enabled}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-2x_rtx_pro_6000_sm120_mtp1_prefix_cache}"
PREFIX_CACHE_STRESS_CASE_NAME="${PREFIX_CACHE_STRESS_CASE_NAME:-user_report_4507780873_prefix_cache_stress}"
PREFIX_CACHE_STRESS_TRIALS="${PREFIX_CACHE_STRESS_TRIALS:-5}"
PREFIX_CACHE_STRESS_FILLER_WORDS="${PREFIX_CACHE_STRESS_FILLER_WORDS:-800}"
PREFIX_CACHE_STRESS_TURNS="${PREFIX_CACHE_STRESS_TURNS:-3}"
PREFIX_CACHE_STRESS_MAX_TOKENS="${PREFIX_CACHE_STRESS_MAX_TOKENS:-256}"
PREFIX_CACHE_STRESS_TEMPERATURE="${PREFIX_CACHE_STRESS_TEMPERATURE:-1.0}"
PREFIX_CACHE_STRESS_TOP_P="${PREFIX_CACHE_STRESS_TOP_P:-1.0}"
B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS:---gpu-memory-utilization 0.977 --disable-custom-all-reduce --default-chat-template-kwargs '{\"thinking\": true}' --compilation-config '{\"cudagraph_mode\":\"FULL_AND_PIECEWISE\",\"custom_ops\":[\"all\"]}'}"

export B200_BASELINE_LABEL B200_BASELINE_VARIANTS B200_BASELINE_PHASES
export RUN_PREFIX_CACHE_STRESS
export B200_TENSOR_PARALLEL_SIZE B200_BLOCK_SIZE B200_KV_CACHE_DTYPE
export SERVE_MAX_MODEL_LEN SERVE_USE_FP4_INDEXER_CACHE SERVE_PREFIX_CACHE_MODE
export GPU_TOPOLOGY_SLUG PREFIX_CACHE_STRESS_CASE_NAME
export PREFIX_CACHE_STRESS_TRIALS PREFIX_CACHE_STRESS_FILLER_WORDS
export PREFIX_CACHE_STRESS_TURNS PREFIX_CACHE_STRESS_MAX_TOKENS
export PREFIX_CACHE_STRESS_TEMPERATURE PREFIX_CACHE_STRESS_TOP_P
export B200_EXTRA_SERVE_ARGS

"${SCRIPT_DIR}/run_b200_baseline.sh"
