#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

# Local SM120 proxy for https://github.com/jasl/vllm/issues/10.
# The reported failure is GB10/SM121 and dual-node specific; this profile keeps
# the same vLLM risk knobs while using a safe default context on dual-card SM120.
B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-sm120_issue10_startup_gate}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-long_context_latency_matrix,prefix_cache_stress,streaming_pressure_matrix}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}"
B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}"
B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-65536}"
SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-enabled}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-2x_rtx_pro_6000_sm120_issue10_proxy}"
# The report used --gpu-memory-utilization 0.83 and
# --max-num-batched-tokens 16384 on GB10. On 96GB RTX PRO 6000, vLLM's CUDA
# graph memory profiler leaves too little KV cache budget for the 128K-class
# local ceiling with those exact values. Keep the local default viable, while
# allowing exact recipe replay through ISSUE10_* overrides.
ISSUE10_GPU_MEMORY_UTILIZATION="${ISSUE10_GPU_MEMORY_UTILIZATION:-0.977}"
ISSUE10_MAX_NUM_BATCHED_TOKENS="${ISSUE10_MAX_NUM_BATCHED_TOKENS:-4096}"
ISSUE10_MAX_NUM_SEQS="${ISSUE10_MAX_NUM_SEQS:-4}"
ISSUE10_ALLOW_HOST_REBOOT_RISK="${ISSUE10_ALLOW_HOST_REBOOT_RISK:-0}"

if (( SERVE_MAX_MODEL_LEN >= 131072 )) && [[ "${ISSUE10_ALLOW_HOST_REBOOT_RISK}" != "1" ]]; then
  cat >&2 <<'EOF'
Refusing to run the issue #10 128K-class SM120 proxy by default.

This shape can leave a GPU in a driver fatal state that requires an OS reboot.
Set ISSUE10_ALLOW_HOST_REBOOT_RISK=1 only on a disposable/debug host where a
reboot is acceptable.
EOF
  exit 2
fi

DG_JIT_USE_NVRTC="${DG_JIT_USE_NVRTC:-0}"
DG_JIT_PRINT_COMPILER_COMMAND="${DG_JIT_PRINT_COMPILER_COMMAND:-1}"
FLASHINFER_DISABLE_VERSION_CHECK="${FLASHINFER_DISABLE_VERSION_CHECK:-1}"
NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-0}"
OMP_NUM_THREADS="${OMP_NUM_THREADS:-8}"
TILELANG_CLEANUP_TEMP_FILES="${TILELANG_CLEANUP_TEMP_FILES:-1}"
VLLM_ALLOW_LONG_MAX_MODEL_LEN="${VLLM_ALLOW_LONG_MAX_MODEL_LEN:-1}"
VLLM_TRITON_MLA_SPARSE="${VLLM_TRITON_MLA_SPARSE:-1}"
VLLM_USE_FLASHINFER_SAMPLER="${VLLM_USE_FLASHINFER_SAMPLER:-1}"

RUN_LONG_CONTEXT_LATENCY_MATRIX="${RUN_LONG_CONTEXT_LATENCY_MATRIX:-1}"
LONG_CONTEXT_LATENCY_CASE_NAME="${LONG_CONTEXT_LATENCY_CASE_NAME:-issue10_startup_latency}"
LONG_CONTEXT_LATENCY_LINE_COUNTS="${LONG_CONTEXT_LATENCY_LINE_COUNTS:-1900}"
LONG_CONTEXT_LATENCY_CONCURRENCY="${LONG_CONTEXT_LATENCY_CONCURRENCY:-1,2}"
LONG_CONTEXT_LATENCY_CACHE_MODES="${LONG_CONTEXT_LATENCY_CACHE_MODES:-cold,warm}"
LONG_CONTEXT_LATENCY_REPEAT_COUNT="${LONG_CONTEXT_LATENCY_REPEAT_COUNT:-1}"
LONG_CONTEXT_LATENCY_MAX_TOKENS="${LONG_CONTEXT_LATENCY_MAX_TOKENS:-64}"
LONG_CONTEXT_LATENCY_PREWARM="${LONG_CONTEXT_LATENCY_PREWARM:-0}"

RUN_PREFIX_CACHE_STRESS="${RUN_PREFIX_CACHE_STRESS:-1}"
PREFIX_CACHE_STRESS_CASE_NAME="${PREFIX_CACHE_STRESS_CASE_NAME:-issue10_prefix_cache_stress}"
PREFIX_CACHE_STRESS_TRIALS="${PREFIX_CACHE_STRESS_TRIALS:-3}"
PREFIX_CACHE_STRESS_FILLER_WORDS="${PREFIX_CACHE_STRESS_FILLER_WORDS:-800}"
PREFIX_CACHE_STRESS_TURNS="${PREFIX_CACHE_STRESS_TURNS:-3}"
PREFIX_CACHE_STRESS_MAX_TOKENS="${PREFIX_CACHE_STRESS_MAX_TOKENS:-128}"

RUN_STREAMING_PRESSURE_MATRIX="${RUN_STREAMING_PRESSURE_MATRIX:-1}"
STREAMING_PRESSURE_MATRIX_CASE_NAME="${STREAMING_PRESSURE_MATRIX_CASE_NAME:-issue10_streaming_pressure}"
STREAMING_PRESSURE_MATRIX_CASE_SPECS="${STREAMING_PRESSURE_MATRIX_CASE_SPECS:-issue10_c2_124k:2:1:4000:64,issue10_c4_59k:4:1:1900:128}"
STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW="${STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW:-0}"

B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS:---gpu-memory-utilization ${ISSUE10_GPU_MEMORY_UTILIZATION} --max-num-seqs ${ISSUE10_MAX_NUM_SEQS} --max-num-batched-tokens ${ISSUE10_MAX_NUM_BATCHED_TOKENS} --load-format safetensors --tokenizer ${MODEL:-deepseek-ai/DeepSeek-V4-Flash} --enable-chunked-prefill --disable-custom-all-reduce --default-chat-template-kwargs '{\"thinking\": true}' --compilation-config '{\"cudagraph_mode\":\"FULL_AND_PIECEWISE\",\"custom_ops\":[\"all\"]}' --override-generation-config '{\"temperature\": 1.0, \"top_p\": 1.0}'}"

export B200_BASELINE_LABEL B200_BASELINE_VARIANTS B200_BASELINE_PHASES
export B200_TENSOR_PARALLEL_SIZE B200_BLOCK_SIZE B200_KV_CACHE_DTYPE
export SERVE_MAX_MODEL_LEN SERVE_USE_FP4_INDEXER_CACHE SERVE_PREFIX_CACHE_MODE
export GPU_TOPOLOGY_SLUG ISSUE10_GPU_MEMORY_UTILIZATION
export ISSUE10_MAX_NUM_BATCHED_TOKENS ISSUE10_MAX_NUM_SEQS
export DG_JIT_USE_NVRTC DG_JIT_PRINT_COMPILER_COMMAND
export FLASHINFER_DISABLE_VERSION_CHECK NCCL_DEBUG NCCL_IB_DISABLE
export OMP_NUM_THREADS TILELANG_CLEANUP_TEMP_FILES
export VLLM_ALLOW_LONG_MAX_MODEL_LEN VLLM_TRITON_MLA_SPARSE
export VLLM_USE_FLASHINFER_SAMPLER
export RUN_LONG_CONTEXT_LATENCY_MATRIX LONG_CONTEXT_LATENCY_CASE_NAME
export LONG_CONTEXT_LATENCY_LINE_COUNTS LONG_CONTEXT_LATENCY_CONCURRENCY
export LONG_CONTEXT_LATENCY_CACHE_MODES LONG_CONTEXT_LATENCY_REPEAT_COUNT
export LONG_CONTEXT_LATENCY_MAX_TOKENS LONG_CONTEXT_LATENCY_PREWARM
export RUN_PREFIX_CACHE_STRESS PREFIX_CACHE_STRESS_CASE_NAME
export PREFIX_CACHE_STRESS_TRIALS PREFIX_CACHE_STRESS_FILLER_WORDS
export PREFIX_CACHE_STRESS_TURNS PREFIX_CACHE_STRESS_MAX_TOKENS
export RUN_STREAMING_PRESSURE_MATRIX STREAMING_PRESSURE_MATRIX_CASE_NAME
export STREAMING_PRESSURE_MATRIX_CASE_SPECS STREAMING_PRESSURE_MATRIX_FAIL_ON_SLOW
export B200_EXTRA_SERVE_ARGS

"${SCRIPT_DIR}/run_b200_baseline.sh"
