#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

if [[ -z "${EXTERNAL_GATE_MAX_MODEL_LEN:-}" ]]; then
  printf 'EXTERNAL_GATE_MAX_MODEL_LEN must be set for external SM120 gates (for example 524288 or 1048576)\n' >&2
  exit 2
fi

B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-sm120_external_reported_${EXTERNAL_GATE_MAX_MODEL_LEN}}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-long_context_latency_matrix,long_context_mixed_arrival,prefix_cache_probe,streaming_pressure_matrix,bench_random_prefill_sweep,eval_longbench2}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-4}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-${EXTERNAL_GATE_MAX_MODEL_LEN}}"
SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-enabled}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-4x_rtx_pro_6000_sm120_external}"
LONG_CONTEXT_LATENCY_CASE_NAME="${LONG_CONTEXT_LATENCY_CASE_NAME:-sm120_external_long_context_latency}"
LONG_CONTEXT_LATENCY_LINE_COUNTS="${LONG_CONTEXT_LATENCY_LINE_COUNTS:-8000,16000,32000}"
LONG_CONTEXT_LATENCY_CONCURRENCY="${LONG_CONTEXT_LATENCY_CONCURRENCY:-1,2}"
LONG_CONTEXT_LATENCY_CACHE_MODES="${LONG_CONTEXT_LATENCY_CACHE_MODES:-cold,warm}"
LONG_CONTEXT_LATENCY_REPEAT_COUNT="${LONG_CONTEXT_LATENCY_REPEAT_COUNT:-2}"
LONG_CONTEXT_LATENCY_MAX_TOKENS="${LONG_CONTEXT_LATENCY_MAX_TOKENS:-128}"
RUN_LONG_CONTEXT_MIXED_ARRIVAL="${RUN_LONG_CONTEXT_MIXED_ARRIVAL:-1}"
LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME:-sm120_external_mixed_long_short_arrival}"
LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS:-tp4_decode_then_long:16000:16000:after_first_token:0:256:128,tp4_long_then_short:32000:192:fixed_delay:2:128:64}"
LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT="${LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT:-2}"
RUN_PREFIX_CACHE_PROBE="${RUN_PREFIX_CACHE_PROBE:-1}"
PREFIX_CACHE_CASE_NAME="${PREFIX_CACHE_CASE_NAME:-user_report_prefix_cache_stability}"
PREFIX_CACHE_LINE_COUNT="${PREFIX_CACHE_LINE_COUNT:-384}"
PREFIX_CACHE_FAIL_ON_REGRESSION="${PREFIX_CACHE_FAIL_ON_REGRESSION:-1}"
RUN_STREAMING_PRESSURE_MATRIX="${RUN_STREAMING_PRESSURE_MATRIX:-1}"
STREAMING_PRESSURE_MATRIX_CASE_SPECS="${STREAMING_PRESSURE_MATRIX_CASE_SPECS:-tp4_512k_c4:4:2:16000:128,tp4_1m_c4:4:2:32000:128,tp4_1m_c6:6:2:32000:128}"
RUN_RANDOM_PREFILL_SWEEP="${RUN_RANDOM_PREFILL_SWEEP:-1}"
RANDOM_PREFILL_INPUT_LENS="${RANDOM_PREFILL_INPUT_LENS:-1024,4096,16384,65536}"
RANDOM_PREFILL_OUTPUT_LEN="${RANDOM_PREFILL_OUTPUT_LEN:-1}"
RANDOM_PREFILL_CONCURRENCY="${RANDOM_PREFILL_CONCURRENCY:-1}"
RUN_LONGBENCH2="${RUN_LONGBENCH2:-1}"
LONGBENCH2_MAX_MODEL_LEN="${LONGBENCH2_MAX_MODEL_LEN:-${EXTERNAL_GATE_MAX_MODEL_LEN}}"
LONGBENCH2_NUM_CONCURRENT="${LONGBENCH2_NUM_CONCURRENT:-1}"

export B200_BASELINE_LABEL B200_BASELINE_VARIANTS B200_BASELINE_PHASES
export B200_TENSOR_PARALLEL_SIZE SERVE_MAX_MODEL_LEN SERVE_USE_FP4_INDEXER_CACHE
export SERVE_PREFIX_CACHE_MODE GPU_TOPOLOGY_SLUG
export LONG_CONTEXT_LATENCY_CASE_NAME LONG_CONTEXT_LATENCY_LINE_COUNTS
export LONG_CONTEXT_LATENCY_CONCURRENCY LONG_CONTEXT_LATENCY_CACHE_MODES
export LONG_CONTEXT_LATENCY_REPEAT_COUNT LONG_CONTEXT_LATENCY_MAX_TOKENS
export RUN_LONG_CONTEXT_MIXED_ARRIVAL LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME
export LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS
export LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT
export RUN_PREFIX_CACHE_PROBE PREFIX_CACHE_CASE_NAME PREFIX_CACHE_LINE_COUNT
export PREFIX_CACHE_FAIL_ON_REGRESSION
export RUN_STREAMING_PRESSURE_MATRIX STREAMING_PRESSURE_MATRIX_CASE_SPECS
export RUN_RANDOM_PREFILL_SWEEP RANDOM_PREFILL_INPUT_LENS
export RANDOM_PREFILL_OUTPUT_LEN RANDOM_PREFILL_CONCURRENCY
export RUN_LONGBENCH2 LONGBENCH2_MAX_MODEL_LEN LONGBENCH2_NUM_CONCURRENT

"${SCRIPT_DIR}/run_b200_baseline.sh"
