#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

B200_BASELINE_LABEL="${B200_BASELINE_LABEL:-sm120_local_quality_gates}"
B200_BASELINE_VARIANTS="${B200_BASELINE_VARIANTS:-mtp}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-acceptance,long_context_probe,long_context_latency_matrix,frontier_context_sweep,ds4_story_recall_semantic,long_context_decode_concurrency,long_context_mixed_arrival,streaming_pressure_matrix,bench_random_prefill_sweep,bench_random_8000x1000,bench_random_256x256,bench_hf_mt_bench,eval_gsm8k}"
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}"
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-131072}"
SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}"
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-disabled}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-2x_rtx_pro_6000_sm120}"
# Dual RTX PRO 6000 128K local default. Keeping max_num_seqs small preserves
# KV headroom under vLLM's CUDA graph memory profiler while still capturing
# FULL_AND_PIECEWISE graphs for the C=1/C=2/C=4 maximum-context target.
# Use the user-feedback throughput profile or PR performance gate for C=8/16/24.
SM120_LOCAL_GPU_MEMORY_UTILIZATION="${SM120_LOCAL_GPU_MEMORY_UTILIZATION:-0.975}"
SM120_LOCAL_MAX_NUM_BATCHED_TOKENS="${SM120_LOCAL_MAX_NUM_BATCHED_TOKENS:-4096}"
SM120_LOCAL_MAX_NUM_SEQS="${SM120_LOCAL_MAX_NUM_SEQS:-4}"
SM120_LOCAL_ENABLE_EXPERT_PARALLEL="${SM120_LOCAL_ENABLE_EXPERT_PARALLEL:-0}"
case "${SM120_LOCAL_ENABLE_EXPERT_PARALLEL}" in
  1|true|TRUE|yes|YES)
    _sm120_local_expert_parallel_arg=" --enable-expert-parallel"
    ;;
  0|false|FALSE|no|NO)
    _sm120_local_expert_parallel_arg=""
    ;;
  *)
    echo "SM120_LOCAL_ENABLE_EXPERT_PARALLEL must be 0/1 or true/false; got '${SM120_LOCAL_ENABLE_EXPERT_PARALLEL}'" >&2
    exit 2
    ;;
esac
_DEFAULT_SM120_LOCAL_EXTRA_SERVE_ARGS="--distributed-executor-backend mp --gpu-memory-utilization ${SM120_LOCAL_GPU_MEMORY_UTILIZATION} --max-num-batched-tokens ${SM120_LOCAL_MAX_NUM_BATCHED_TOKENS} --max-num-seqs ${SM120_LOCAL_MAX_NUM_SEQS}${_sm120_local_expert_parallel_arg} --compilation-config '{\"cudagraph_mode\":\"FULL_AND_PIECEWISE\",\"custom_ops\":[\"all\"]}'"
B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS:-${_DEFAULT_SM120_LOCAL_EXTRA_SERVE_ARGS}}"
LONG_CONTEXT_LATENCY_CASE_NAME="${LONG_CONTEXT_LATENCY_CASE_NAME:-sm120_local_59k_124k_latency}"
LONG_CONTEXT_LATENCY_LINE_COUNTS="${LONG_CONTEXT_LATENCY_LINE_COUNTS:-1900,4000}"
LONG_CONTEXT_LATENCY_CONCURRENCY="${LONG_CONTEXT_LATENCY_CONCURRENCY:-1,2}"
LONG_CONTEXT_LATENCY_CACHE_MODES="${LONG_CONTEXT_LATENCY_CACHE_MODES:-cold}"
LONG_CONTEXT_LATENCY_REPEAT_COUNT="${LONG_CONTEXT_LATENCY_REPEAT_COUNT:-3}"
LONG_CONTEXT_LATENCY_MAX_TOKENS="${LONG_CONTEXT_LATENCY_MAX_TOKENS:-64}"
LONG_CONTEXT_LATENCY_PREWARM="${LONG_CONTEXT_LATENCY_PREWARM:-1}"
RUN_FRONTIER_CONTEXT_SWEEP="${RUN_FRONTIER_CONTEXT_SWEEP:-1}"
FRONTIER_CONTEXT_SWEEP_CASE_NAME="${FRONTIER_CONTEXT_SWEEP_CASE_NAME:-sm120_local_frontier_context_sweep}"
FRONTIER_CONTEXT_SWEEP_PROMPT_FILES="${FRONTIER_CONTEXT_SWEEP_PROMPT_FILES:-${REPO_ROOT}/prompts/long_context/ds4_story_recall.txt,${REPO_ROOT}/prompts/long_context/ds4_security_audit.txt}"
FRONTIER_CONTEXT_SWEEP_FRONTIERS="${FRONTIER_CONTEXT_SWEEP_FRONTIERS:-8192,16384,32768,65536,98304,124000}"
FRONTIER_CONTEXT_SWEEP_REPEAT_COUNT="${FRONTIER_CONTEXT_SWEEP_REPEAT_COUNT:-1}"
FRONTIER_CONTEXT_SWEEP_MAX_TOKENS="${FRONTIER_CONTEXT_SWEEP_MAX_TOKENS:-128}"
FRONTIER_CONTEXT_SWEEP_PREWARM="${FRONTIER_CONTEXT_SWEEP_PREWARM:-1}"
RUN_DS4_STORY_RECALL_SEMANTIC="${RUN_DS4_STORY_RECALL_SEMANTIC:-1}"
DS4_STORY_RECALL_CASE_NAME="${DS4_STORY_RECALL_CASE_NAME:-sm120_local_ds4_story_recall_semantic}"
DS4_STORY_RECALL_PROMPT_FILE="${DS4_STORY_RECALL_PROMPT_FILE:-${REPO_ROOT}/prompts/long_context/ds4_story_recall.txt}"
DS4_STORY_RECALL_MAX_TOKENS="${DS4_STORY_RECALL_MAX_TOKENS:-128}"
RUN_LONG_CONTEXT_DECODE_CONCURRENCY="${RUN_LONG_CONTEXT_DECODE_CONCURRENCY:-1}"
LONG_CONTEXT_DECODE_CASE_NAME="${LONG_CONTEXT_DECODE_CASE_NAME:-sm120_local_124k_decode_concurrency}"
LONG_CONTEXT_DECODE_LINE_COUNTS="${LONG_CONTEXT_DECODE_LINE_COUNTS:-4000}"
LONG_CONTEXT_DECODE_CONCURRENCY="${LONG_CONTEXT_DECODE_CONCURRENCY:-1,2}"
LONG_CONTEXT_DECODE_CACHE_MODES="${LONG_CONTEXT_DECODE_CACHE_MODES:-cold}"
LONG_CONTEXT_DECODE_REPEAT_COUNT="${LONG_CONTEXT_DECODE_REPEAT_COUNT:-1}"
LONG_CONTEXT_DECODE_MAX_TOKENS="${LONG_CONTEXT_DECODE_MAX_TOKENS:-256}"
RUN_LONG_CONTEXT_MIXED_ARRIVAL="${RUN_LONG_CONTEXT_MIXED_ARRIVAL:-1}"
LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME:-sm120_local_mixed_long_short_arrival}"
LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS="${LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS:-decode_then_59k:1900:1900:after_first_token:0:256:128,long_then_short:4000:192:fixed_delay:2:128:64}"
LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT="${LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT:-3}"
RUN_PREFIX_CACHE_PROBE="${RUN_PREFIX_CACHE_PROBE:-0}"
PREFIX_CACHE_CASE_NAME="${PREFIX_CACHE_CASE_NAME:-user_report_mtp1_prefix_cache_stability_proxy}"
PREFIX_CACHE_LINE_COUNT="${PREFIX_CACHE_LINE_COUNT:-384}"
PREFIX_CACHE_MAX_TOKENS="${PREFIX_CACHE_MAX_TOKENS:-64}"
PREFIX_CACHE_FAIL_ON_REGRESSION="${PREFIX_CACHE_FAIL_ON_REGRESSION:-1}"
RUN_STREAMING_PRESSURE_MATRIX="${RUN_STREAMING_PRESSURE_MATRIX:-1}"
STREAMING_PRESSURE_MATRIX_CASE_SPECS="${STREAMING_PRESSURE_MATRIX_CASE_SPECS:-short_c4:4:3:1200:128,issue7_5k_c4:4:3:192:128,long_c2:2:2:4000:128,long_c4:4:2:2400:128}"
RUN_RANDOM_PREFILL_SWEEP="${RUN_RANDOM_PREFILL_SWEEP:-1}"
RANDOM_PREFILL_INPUT_LENS="${RANDOM_PREFILL_INPUT_LENS:-1024,4096,16384,65536}"
RANDOM_PREFILL_OUTPUT_LEN="${RANDOM_PREFILL_OUTPUT_LEN:-1}"
RANDOM_PREFILL_CONCURRENCY="${RANDOM_PREFILL_CONCURRENCY:-1}"
RANDOM_PREFILL_NUM_PROMPTS="${RANDOM_PREFILL_NUM_PROMPTS:-8}"
RUN_RANDOM_8K1K="${RUN_RANDOM_8K1K:-1}"
RANDOM_8K1K_INPUT_LEN="${RANDOM_8K1K_INPUT_LEN:-8000}"
RANDOM_8K1K_OUTPUT_LEN="${RANDOM_8K1K_OUTPUT_LEN:-1000}"
RANDOM_8K1K_CONCURRENCY="${RANDOM_8K1K_CONCURRENCY:-1,2,4}"
RANDOM_8K1K_NUM_PROMPTS="${RANDOM_8K1K_NUM_PROMPTS:-80}"
RUN_RANDOM_256X256="${RUN_RANDOM_256X256:-1}"
RANDOM_256X256_INPUT_LEN="${RANDOM_256X256_INPUT_LEN:-256}"
RANDOM_256X256_OUTPUT_LEN="${RANDOM_256X256_OUTPUT_LEN:-256}"
RANDOM_256X256_CONCURRENCY="${RANDOM_256X256_CONCURRENCY:-1,4}"
RANDOM_256X256_NUM_PROMPTS="${RANDOM_256X256_NUM_PROMPTS:-80}"
LM_EVAL_NUM_FEWSHOT="${LM_EVAL_NUM_FEWSHOT:-5}"
LM_EVAL_LIMIT="${LM_EVAL_LIMIT:-200}"
MTP_LM_EVAL_NUM_CONCURRENT="${MTP_LM_EVAL_NUM_CONCURRENT:-4}"

export B200_BASELINE_LABEL B200_BASELINE_VARIANTS B200_BASELINE_PHASES
export B200_TENSOR_PARALLEL_SIZE SERVE_MAX_MODEL_LEN SERVE_USE_FP4_INDEXER_CACHE
export SERVE_PREFIX_CACHE_MODE GPU_TOPOLOGY_SLUG
export SM120_LOCAL_GPU_MEMORY_UTILIZATION SM120_LOCAL_MAX_NUM_BATCHED_TOKENS
export SM120_LOCAL_MAX_NUM_SEQS SM120_LOCAL_ENABLE_EXPERT_PARALLEL
export B200_EXTRA_SERVE_ARGS
export LONG_CONTEXT_LATENCY_CASE_NAME LONG_CONTEXT_LATENCY_LINE_COUNTS
export LONG_CONTEXT_LATENCY_CONCURRENCY LONG_CONTEXT_LATENCY_CACHE_MODES
export LONG_CONTEXT_LATENCY_REPEAT_COUNT LONG_CONTEXT_LATENCY_MAX_TOKENS
export LONG_CONTEXT_LATENCY_PREWARM
export RUN_FRONTIER_CONTEXT_SWEEP FRONTIER_CONTEXT_SWEEP_CASE_NAME
export FRONTIER_CONTEXT_SWEEP_PROMPT_FILES FRONTIER_CONTEXT_SWEEP_FRONTIERS
export FRONTIER_CONTEXT_SWEEP_REPEAT_COUNT FRONTIER_CONTEXT_SWEEP_MAX_TOKENS
export FRONTIER_CONTEXT_SWEEP_PREWARM
export RUN_DS4_STORY_RECALL_SEMANTIC DS4_STORY_RECALL_CASE_NAME
export DS4_STORY_RECALL_PROMPT_FILE DS4_STORY_RECALL_MAX_TOKENS
export RUN_LONG_CONTEXT_DECODE_CONCURRENCY LONG_CONTEXT_DECODE_CASE_NAME
export LONG_CONTEXT_DECODE_LINE_COUNTS LONG_CONTEXT_DECODE_CONCURRENCY
export LONG_CONTEXT_DECODE_CACHE_MODES LONG_CONTEXT_DECODE_REPEAT_COUNT
export LONG_CONTEXT_DECODE_MAX_TOKENS
export RUN_LONG_CONTEXT_MIXED_ARRIVAL LONG_CONTEXT_MIXED_ARRIVAL_CASE_NAME
export LONG_CONTEXT_MIXED_ARRIVAL_CASE_SPECS
export LONG_CONTEXT_MIXED_ARRIVAL_REPEAT_COUNT
export RUN_PREFIX_CACHE_PROBE PREFIX_CACHE_CASE_NAME PREFIX_CACHE_LINE_COUNT
export PREFIX_CACHE_MAX_TOKENS PREFIX_CACHE_FAIL_ON_REGRESSION
export RUN_STREAMING_PRESSURE_MATRIX STREAMING_PRESSURE_MATRIX_CASE_SPECS
export RUN_RANDOM_PREFILL_SWEEP RANDOM_PREFILL_INPUT_LENS
export RANDOM_PREFILL_OUTPUT_LEN RANDOM_PREFILL_CONCURRENCY
export RANDOM_PREFILL_NUM_PROMPTS
export RUN_RANDOM_8K1K RANDOM_8K1K_INPUT_LEN RANDOM_8K1K_OUTPUT_LEN
export RANDOM_8K1K_CONCURRENCY RANDOM_8K1K_NUM_PROMPTS
export RUN_RANDOM_256X256 RANDOM_256X256_INPUT_LEN RANDOM_256X256_OUTPUT_LEN
export RANDOM_256X256_CONCURRENCY RANDOM_256X256_NUM_PROMPTS
export LM_EVAL_NUM_FEWSHOT LM_EVAL_LIMIT MTP_LM_EVAL_NUM_CONCURRENT

"${SCRIPT_DIR}/run_b200_baseline.sh"
