#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/run_context.sh"
load_harness_env

PERF_BASELINE_JSON="${PERF_BASELINE_JSON:-}"
if [[ -z "${PERF_BASELINE_JSON}" ]]; then
  echo "PERF_BASELINE_JSON is required; point it at an accepted bench_random_8000x1000 bench.json" >&2
  exit 2
fi
if [[ ! -f "${PERF_BASELINE_JSON}" ]]; then
  echo "PERF_BASELINE_JSON does not exist: ${PERF_BASELINE_JSON}" >&2
  exit 2
fi

MODEL="${MODEL:-deepseek-ai/DeepSeek-V4-Flash}"
HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-8080}"
B200_VLLM_REPO="${B200_VLLM_REPO:-/workspace/vllm}"
B200_VLLM_VENV="${B200_VLLM_VENV:-${B200_VLLM_REPO}/.venv}"
PYTHON="${PYTHON:-${B200_VLLM_VENV}/bin/python}"
VLLM_BIN="${VLLM_BIN:-${B200_VLLM_VENV}/bin/vllm}"
RUN_TIMESTAMP="${RUN_TIMESTAMP:-$(date +%Y%m%d%H%M%S)}"
BRANCH_NAME="${BRANCH_NAME:-$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown-branch)}"
BRANCH_SLUG="$(printf '%s' "${BRANCH_NAME}" | sed -E 's#[/[:space:]]+#_#g; s#[^A-Za-z0-9_.-]#_#g')"
BRANCH_SLUG="${BRANCH_SLUG:-unknown-branch}"
GPU_TOPOLOGY_SLUG="${GPU_TOPOLOGY_SLUG:-$(detect_gpu_topology_slug)}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-${REPO_ROOT}/artifacts}"
SM120_PR_PERF_LABEL="${SM120_PR_PERF_LABEL:-sm120_pr_performance_regression_gate}"
SM120_PR_PERF_ROOT="${OUT_DIR:-${ARTIFACT_ROOT}/${BRANCH_SLUG}/${GPU_TOPOLOGY_SLUG}/${SM120_PR_PERF_LABEL}/${RUN_TIMESTAMP}}"

SM120_PR_PERF_VARIANT="${SM120_PR_PERF_VARIANT:-mtp}"
SM120_PR_PERF_CONCURRENCY="${SM120_PR_PERF_CONCURRENCY:-1,2,4}"
SM120_PR_PERF_MIN_OUTPUT_SPEEDUP="${SM120_PR_PERF_MIN_OUTPUT_SPEEDUP:-0.95}"
SM120_PR_PERF_MIN_TPOT_SPEEDUP="${SM120_PR_PERF_MIN_TPOT_SPEEDUP:-0.95}"
SM120_PR_PERF_MIN_SPEC_ACCEPTANCE_RATIO="${SM120_PR_PERF_MIN_SPEC_ACCEPTANCE_RATIO:-0.98}"
SM120_PR_PERF_MIN_SPEC_ACCEPTANCE_PERCENT="${SM120_PR_PERF_MIN_SPEC_ACCEPTANCE_PERCENT:-65.0}"

SM120_PR_PERF_GPU_MEMORY_UTILIZATION="${SM120_PR_PERF_GPU_MEMORY_UTILIZATION:-0.975}"
SM120_PR_PERF_MAX_NUM_BATCHED_TOKENS="${SM120_PR_PERF_MAX_NUM_BATCHED_TOKENS:-4096}"
SM120_PR_PERF_MAX_NUM_SEQS="${SM120_PR_PERF_MAX_NUM_SEQS:-4}"
_DEFAULT_SM120_PR_PERF_EXTRA_SERVE_ARGS="--gpu-memory-utilization ${SM120_PR_PERF_GPU_MEMORY_UTILIZATION} --max-num-batched-tokens ${SM120_PR_PERF_MAX_NUM_BATCHED_TOKENS} --max-num-seqs ${SM120_PR_PERF_MAX_NUM_SEQS} --enable-expert-parallel --compilation-config '{\"cudagraph_mode\":\"FULL_AND_PIECEWISE\",\"custom_ops\":[\"all\"]}'"
B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS:-${_DEFAULT_SM120_PR_PERF_EXTRA_SERVE_ARGS}}"

RANDOM_8K1K_INPUT_LEN="${RANDOM_8K1K_INPUT_LEN:-8000}"
RANDOM_8K1K_OUTPUT_LEN="${RANDOM_8K1K_OUTPUT_LEN:-1000}"
RANDOM_8K1K_NUM_PROMPTS="${RANDOM_8K1K_NUM_PROMPTS:-80}"
RANDOM_8K1K_BENCH_TIMEOUT="${RANDOM_8K1K_BENCH_TIMEOUT:-3600}"
B200_BASELINE_PHASES="${B200_BASELINE_PHASES:-bench_random_8000x1000}"

mkdir -p "${SM120_PR_PERF_ROOT}"

OUT_DIR="${SM120_PR_PERF_ROOT}/candidate" \
MODEL="${MODEL}" HOST="${HOST}" PORT="${PORT}" \
B200_VLLM_REPO="${B200_VLLM_REPO}" B200_VLLM_VENV="${B200_VLLM_VENV}" \
PYTHON="${PYTHON}" VLLM_BIN="${VLLM_BIN}" \
B200_BASELINE_LABEL="${SM120_PR_PERF_LABEL}_candidate" \
ARTIFACT_ARCHIVE_PREVIOUS=0 \
B200_BASELINE_VARIANTS="${SM120_PR_PERF_VARIANT}" \
B200_BASELINE_PHASES="${B200_BASELINE_PHASES}" \
B200_TENSOR_PARALLEL_SIZE="${B200_TENSOR_PARALLEL_SIZE:-2}" \
B200_BLOCK_SIZE="${B200_BLOCK_SIZE:-256}" \
B200_KV_CACHE_DTYPE="${B200_KV_CACHE_DTYPE:-fp8}" \
SERVE_MAX_MODEL_LEN="${SERVE_MAX_MODEL_LEN:-131072}" \
SERVE_PREFIX_CACHE_MODE="${SERVE_PREFIX_CACHE_MODE:-disabled}" \
SERVE_USE_FP4_INDEXER_CACHE="${SERVE_USE_FP4_INDEXER_CACHE:-0}" \
B200_EXTRA_SERVE_ARGS="${B200_EXTRA_SERVE_ARGS}" \
RUN_RANDOM_8K1K=1 \
RANDOM_8K1K_INPUT_LEN="${RANDOM_8K1K_INPUT_LEN}" \
RANDOM_8K1K_OUTPUT_LEN="${RANDOM_8K1K_OUTPUT_LEN}" \
RANDOM_8K1K_CONCURRENCY="${SM120_PR_PERF_CONCURRENCY}" \
RANDOM_8K1K_NUM_PROMPTS="${RANDOM_8K1K_NUM_PROMPTS}" \
RANDOM_8K1K_BENCH_TIMEOUT="${RANDOM_8K1K_BENCH_TIMEOUT}" \
"${SCRIPT_DIR}/run_b200_baseline.sh"

CANDIDATE_JSON="${SM120_PR_PERF_ROOT}/candidate/${SM120_PR_PERF_VARIANT}/bench_random_8000x1000/bench.json"
if [[ ! -f "${CANDIDATE_JSON}" ]]; then
  echo "candidate bench JSON missing: ${CANDIDATE_JSON}" >&2
  exit 1
fi

"${PYTHON}" -m ds4_harness.cli bench-compare \
  --baseline-json "${PERF_BASELINE_JSON}" \
  --candidate-json "${CANDIDATE_JSON}" \
  --baseline-label "accepted" \
  --candidate-label "candidate" \
  --concurrency "${SM120_PR_PERF_CONCURRENCY}" \
  --fail-on-regression \
  --min-output-speedup "${SM120_PR_PERF_MIN_OUTPUT_SPEEDUP}" \
  --min-tpot-speedup "${SM120_PR_PERF_MIN_TPOT_SPEEDUP}" \
  --min-spec-acceptance-ratio "${SM120_PR_PERF_MIN_SPEC_ACCEPTANCE_RATIO}" \
  --min-spec-acceptance-percent "${SM120_PR_PERF_MIN_SPEC_ACCEPTANCE_PERCENT}" \
  --json-output "${SM120_PR_PERF_ROOT}/performance_regression_gate.json" \
  --markdown-output "${SM120_PR_PERF_ROOT}/performance_regression_gate.md"

echo "wrote ${SM120_PR_PERF_ROOT}"
